title: Tri2Repo
description: "August 2023 to June 2024"
owner_name: Ryan Liao
github_username: rliao569
github_repo: "Tri2Repo"
baseurl: "/Tri2Repo"
#remote_theme: jekyll/minima
remote_theme: thedevslot/WhatATheme
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/rliao569"}
    - { platform: github, user_url: "https://github.com/AaronH1234"}
    - { platform: github, user_url: "https://github.com/JasonGuan1012"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
